sudo: required
services:
  - docker

before_install: 
  - docker build -t zigoto/fibo-client -f ./client/docker/Dockerfile.dev ./client

script: 
  - docker run -e CI=true zigoto/fibo-client npm test

after_success: 
  - docker build -t zigoto/fibo-client -f ./client/docker/Dockerfile ./client
  - docker build -t zigoto/fibo-nginx -f ./deployments/nginx/Dockerfile ./deployments/nginx
  - docker build -t zigoto/fibo-server -f ./server/docker/Dockerfile .
  - docker build -t zigoto/fibo-worker -f ./worker/docker/Dockerfile .

  - echo "$DOCKER_PASSWORD" | $docker login -u "$DOCKER_USER" --password-stdin
  - docker push zigoto/fibo-client
  - docker push zigoto/fibo-nginx
  - docker push zigoto/fibo-server
  - docker push zigoto/fibo-worker
  
deploy:
    provider: elasticbeanstalk
    region: 'us-east-1'
    app: 'multi-docker'
    env: 'MultiDocker-env'
    bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
    bucket_path: 'docker-multi'
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY