version: "3"
services:
  client:
    image: "zigoto/fibo-client"
    mem_limit: 128m
    hostname: client
  server:
    image: "zigoto/fibo-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "zigoto/fibo-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
  nginx:
    image: "zigoto/fibo-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"