version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: pw
  redis:
    image: redis:latest
    container_name: redis
    
