version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: pw
  redis:
    image: redis:latest
    container_name: redis
  server:
    build:
      dockerfile: server/docker/Dockerfile.dev
      context: ../../
    container_name: server
    volumes:
      - /app/server/node_modules
      - ../../server:/app/server
    environment:
      - REDIS_HOST=redis
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDB=postgres
      - PGPASS=pw
      - PGPORT=5432
  worker:
    build:
      dockerfile: worker/docker/Dockerfile.dev
      context: ../../
    volumes:
      - /app/worker/node_modules
      - ../../worker:/app/worker
    environment:
      - REDIS_HOST=redis    